In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [3]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()
model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
model.get_weights()

[array([[ 0.23992372, -1.1111804 ],
        [ 0.43990648, -0.60634816]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.15315318],
        [ 0.33022094]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1, 0.1],
        [ 0.1 ,  0.1 ]], dtype=np.float32),
 np.array([0.1, 0.1], dtype=np.float32),
 np.array([[0.1],
        [0.1 ]], dtype=np.float32),
 np.array([0.1], dtype=np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0.1, 0.1], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [11]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)

In [16]:
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [17]:
model.fit(df.iloc[:, 0:-1].values, df['placed'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 4ms/step - loss: 0.7009
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 0.7004
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6997
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6999
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6995
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6993
Epoch 7/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6993
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6992
Epoch 9/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6992
Epoch 10/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6990
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6991
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6993
Epoch 13/75
4/4 [==============================] - 0s 3ms/step - loss: 0.

In [18]:
model.get_weights()

[array([[0.09153617, 0.09153617],
        [0.06997074, 0.06997074]], dtype=float32),
 array([0.04664211, 0.04664211], dtype=float32),
 array([[0.07686043],
        [0.07686043]], dtype=float32),
 array([0.06795564], dtype=float32)]