In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.get_weights()

[array([[-0.46889728, -0.98072326],
        [ 0.8267039 ,  0.0595386 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.29517055],
        [-1.3045859 ]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1, 0.1],
        [ 0.1 ,  0.1 ]], dtype=np.float32),
 np.array([0.1, 0.1], dtype=np.float32),
 np.array([[0.1],
        [0.1 ]], dtype=np.float32),
 np.array([0.1], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0.1, 0.1], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)

In [ ]:
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 26.6594
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 26.3315
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 26.0033
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 25.6797
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 25.3219
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 24.9919
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6141
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 24.2244
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 23.8388
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 23.4551
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 23.0114
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 22.5986
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste

In [ ]:
model.get_weights()

[array([[0.36922202, 0.36922202],
        [0.36180654, 0.36180654]], dtype=float32),
 array([0.3681848, 0.3681848], dtype=float32),
 array([[0.36710072],
        [0.36710072]], dtype=float32),
 array([0.30228335], dtype=float32)]